[files]
inputs = [
]
outputs = [
]
scripts = [
]

[dok]
docker_image = "chiral.sakuracr.jp/biobb_wf_protein-complex_md_setup:latest"
commands = [
  "run_dok.sh",
  "https://raw.githubusercontent.com/chiral-data/application-examples/refs/heads/v0.2.3-add-gromacs-py/g/gromacs/protein_ligand/job_dok.sh",
]

# DOK plan options
plan = "v100-32gb"
# plan = "h100-80gb"
