# Use NVIDIA CUDA base image with Python
FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    TXGEMMA_CACHE="/opt/txgemma_cache"

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-dev \
    git \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a symbolic link for python
RUN ln -sf /usr/bin/python3 /usr/bin/python

# Create TxGemma cache directory
RUN mkdir -p ${TXGEMMA_CACHE}

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Install dependencies in a fresh environment
RUN pip install --no-cache-dir accelerate
RUN pip install --no-cache-dir bitsandbytes
RUN pip install --no-cache-dir huggingface_hub
RUN pip install --no-cache-dir transformers

# Create a working directory
WORKDIR /workspace

# Copy the launching script run.sh from the project folder @common
COPY run_dok.sh /workspace/run_dok.sh

ENTRYPOINT ["/bin/sh"]
