FROM python:3.8

RUN pip install lightdock

# Create a working directory
WORKDIR /workspace

# Copy the launching script run.sh from the project folder @common
COPY run_dok.sh /workspace/run_dok.sh

ENTRYPOINT ["/bin/sh"]
