[files]
inputs = [
]
outputs = [
]
scripts = [
]

[dok]
docker_image = "chiral.sakuracr.jp/mypresto_sievgene:latest"

commands = [
  "run.sh",
  "https://raw.githubusercontent.com/chiral-data/application-examples/refs/heads/v0.2.3-add-myPresto/m/myPresto/sievgene/job_4hp0.sh",
]

# DOK plan options
plan = "v100-32gb"
# plan = "h100-80gb"
