# Use NVIDIA Pre-built Gromacs Image 
FROM nvcr.io/hpc/gromacs:2023.2

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a working directory
WORKDIR /workspace

# Copy the launching script run.sh from the project folder @common
COPY run_dok.sh /workspace/run_dok.sh

ENTRYPOINT ["/bin/sh"]
