[files]
inputs = [
]
outputs = [
]
scripts = [
]

[dok]
docker_image = "chiral.sakuracr.jp/gromacs_2023_2_rebuild:latest"
commands = [
  "run.sh",
  "https://raw.githubusercontent.com/chiral-data/application-examples/refs/heads/v0.2.3-fix-gromacs/g/gromacs/lysozyme/job_dok.sh",
]

# DOK plan options
plan = "v100-32gb"
# plan = "h100-80gb"
