[files]
inputs = [
    "prot_no_msa.yaml"
]
outputs = [
    "prot_no_msa_model_0.cif",
    "confidence_prot_no_msa_model_0.json",
#    "pae_prot_no_msa_model_0.npz",
#    "pde_prot_no_msa_model_0.npz",
    "plddt_prot_no_msa_model_0.npz",
    "prot_no_msa.npz",
#    "prot_no_msa_model_diffusion_samples-1.cif"
]
scripts = [
  # "job.sh"
  # "curl -O https://raw.githubusercontent.com/chiral-data/application-examples/refs/heads/v0.2.3_boltz/b/boltz/boltz_dok/job.sh | bash"
]

[dok]
docker_image = "chiral.sakuracr.jp/boltz1_rebuild:latest"

# http_port = 11434
# DOK plan options
plan = "v100-32gb"
# plan = "h100-80gb"
