[files]
inputs = [
  "job.sh"
]
outputs = [
]
scripts = [
]

[dok]
docker_image = "chiral.sakuracr.jp/boltz1_rebuild:latest"
commands = [
  "run.sh",
  "https://raw.githubusercontent.com/chiral-data/application-examples/refs/heads/v0.2.3/b/boltz/boltz_dok/job.sh",
]

# DOK plan options
# plan = "v100-32gb"
plan = "h100-80gb"
